version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 0
  labels:
  - dependencies
  - govuk-pay
  - javascript
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 0
  labels:
  - dependencies
  - govuk-pay
  - github_actions
