version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "development"
          update_type: "security"
      - match:
          dependency_type: "production"
          update_type: "all"
