name: Check for unmerged release PR

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  check_merge:
    uses: alphagov/pay-ci/.github/workflows/_prevent-merge-if-automated-release-open.yml@master
    secrets: inherit # pragma: allowlist secret
